# Generated by Django 3.0 on 2021-07-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deepureuser',
            options={'verbose_name': '用户注册表', 'verbose_name_plural': '用户注册表'},
        ),
        migrations.AlterModelTable(
            name='deepureuser',
            table='deepure_user',
        ),
    ]
