# Generated by Django 3.0 on 2021-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210727_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepureuser',
            name='bmi',
            field=models.CharField(max_length=15, verbose_name='bim'),
        ),
        migrations.AlterField(
            model_name='deepureuser',
            name='bodyfatratio',
            field=models.CharField(max_length=15, verbose_name='体脂率'),
        ),
    ]
